---
- name: Install Java, .NET, and Node.js
  hosts: all
  tasks:
  - name: Install Java
    become: yes
    when: "'Ubuntu' in ansible_facts['distribution']"
    apt:
      name: default-jdk
      update_cache: yes
  - name: Import Microsoft signing key for .NET
    become: yes
    when: "'Ubuntu' in ansible_facts['distribution']"
    shell: |
      wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
  - name: Install .NET runtime
    become: yes
    when: "'Ubuntu' in ansible_facts['distribution']"
    apt:
      name: aspnetcore-runtime-3.1
      state: present
      update_cache: yes
  - name: Install Node.js package manager
    become: yes
    when: "'Ubuntu' in ansible_facts['distribution']"
    shell: |
      sudo apt-get install curl
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - name: Install Node.js
    become: yes
    when: "'Ubuntu' in ansible_facts['distribution']"
    apt:
      name: nodejs
      state: present
      update_cache: yes
  - name: Install Java
    become: yes
    when: "'CentOS' in ansible_facts['distribution']"
    yum:
      name: java-11-openjdk-devel
      state: present
  - name: Import Microsoft signing key for .NET
    become: yes
    when: "'CentOS' in ansible_facts['distribution']"
    shell: |
      sudo rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
  - name: Install .NET runtime
    become: yes
    when: "'CentOS' in ansible_facts['distribution']"
    yum:
      name: aspnetcore-runtime-3.1
      state: present
  - name: Install Node.js package manager
    become: yes
    when: "'CentOS' in ansible_facts['distribution']"
    shell: |
      curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  - name: Install Node.js
    become: yes
    when: "'CentOS' in ansible_facts['distribution']"
    yum:
      name: nodejs
      state: present
