---
pool:
  name: 'default'
  vmImage: 'ubuntu-latest'
trigger:
- main

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'path'
    jdkDirectory:  /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    goals: 'package'
    mavenVersionOption: 'path'
    mavenDirectory: /usr/share/maven
 